### ISSUE TITLE
ERROR: either a proxy or auth address must be set using --proxy, --auth-server or configuration

### ISSUE THREAD

**Issue by mordamax** [teleport-actions/root#44]
Hello team

Out of a sudden, today `teleport-actions/auth-application@v2` stopped working with the error

> ERROR: either a proxy or auth address must be set using --proxy, --auth-server or configuration

action setup:

```yml
      - name: Install Teleport
        uses: teleport-actions/setup@v1.0.6
        with:
          version: 16.0.4 # changed today from 16.0.3, but doesn't work on both version

      - name: Authenticate with Teleport (Staging)
        id: teleport-auth-stg
        uses: teleport-actions/auth-application@v2
        with:
          proxy: ${{ env.TELEPORT_PROXY }} # teleport.example.io:443
          token: ${{ env.TELEPORT_TOKEN }} # token
          certificate-ttl: 1h
          app: cms-staging
          anonymous-telemetry: 1
```

Full output of step:

```
Run teleport-actions/auth-application@v2
  with:
    proxy: teleport.example.io:443
    token: token
    certificate-ttl: 1h
    app: cms-staging
    anonymous-telemetry: 1
(https://github.com/org/repo/actions/runs/9797930390/job/27055537266#step:4:3)
/opt/hostedtoolcache/teleport/16.0.[4](https://github.com/org/repo/actions/runs/9797930390/job/27055537266#step:4:4)-linux-amd64/x64/tbot version
Teleport v16.0.4 git:v16.0.4-0-gc733a8b go1.22.[5](https://github.com/org/repo/actions/runs/9797930390/job/27055537266#step:4:5)
detected tbot version: 1[6](https://github.com/org/repo/actions/runs/9797930390/job/27055537266#step:4:6).0.4
Invoking tbot with configuration at /home/runner/work/_temp/[7](https://github.com/org/repo/actions/runs/9797930390/job/27055537266#step:4:7)b78d7af-015a-4305-8dfb-bacf9b909[8](https://github.com/org/repo/actions/runs/9797930390/job/27055537266#step:4:8)e9/bot-config.yaml
/opt/hostedtoolcache/teleport/16.0.4-linux-amd64/x64/tbot start -c /home/runner/work/_temp/7b78d7af-015a-4305-8dfb-bacf[9](https://github.com/org/repo/actions/runs/9797930390/job/27055537266#step:4:9)b9098e9/bot-config.yaml
2024-07-04T17:12:31Z INFO [TBOT]      Waiting for anonymous telemetry to finish sending before exiting. Press CTRL-C to cancel wait_time:[10](https://github.com/org/repo/actions/runs/9797930390/job/27055537266#step:4:10)s tbot/main.go:506
2024-07-04T17:12:31Z INFO [TBOT]      Anonymous telemetry is enabled. Find out more about Machine ID's anonymous telemetry at https://goteleport.com/docs/machine-id/reference/telemetry/ tbot/anonymous_telemetry.go:87
ERROR: either a proxy or auth address must be set using --proxy, --auth-server or configuration
Error: Error: The process '/opt/hostedtoolcache/teleport/[16](https://github.com/org/repo/actions/runs/9797930390/job/27055537266#step:4:17).0.4-linux-amd64/x64/tbot' failed with exit code 1
```

Here's config in tmp folder:

```
Run CONFIG_FILE=$(find /home/runner/work/_temp/ -name 'bot-config.yaml' | head -n 1)
version: v2
auth_server: teleport.example.io:443
oneshot: true
onboarding:
  join_method: github
  token: token
  ca_pins: []
storage:
  type: memory
outputs:
  - type: application
    destination:
      type: directory
      symlinks: try-secure
      path: /home/runner/work/_temp/30e9cea6-e261-4[11](https://github.com/org/repo/actions/runs/9798156051/job/27056087601#step:9:12)7-8274-2fb1c48146b5
    roles: []
    app_name: cms-staging
certificate_ttl: 1h
```

I checked action code, looks like it didn't change, the strange thing is that this morning it did work well, but once, and then stopped with these errors

UPD: if i use raw installation

```
      - name: Install Teleport CLI
        run: |
          curl -L -o teleport-v16.0.3-linux-amd64-bin.tar.gz https://get.gravitational.com/teleport-v16.0.3-linux-amd64-bin.tar.gz
          tar -xzvf teleport-v16.0.3-linux-amd64-bin.tar.gz
          sudo mv teleport/tctl teleport/teleport teleport/tbot /usr/local/bin/
          teleport version
```

and config above

```
      - name: Authenticate with Teleport (Staging)
        run: |
          tbot start -c ./teleport-config-stg.yaml
```

then it works well, so at that point, it doesn't make sense to use action
