### ISSUE TITLE
`teleport-auth`: Provide ability to set `allow_reissue` flag.

### ISSUE THREAD

**Issue by strideynet** [teleport-actions/root#51]
In the core `tbot` config, we've added an `allow_reissue` field:

```yaml
 services:
  - type: identity
    destination:
      type: directory
      path: ./tbot-user
    ssh_config: 'off'
    allow_reissue: true
```

We should allow this to be specified as a parameter to the `teleport-auth` action and passed thru to the `tbot` config.

Users can workaround via https://goteleport.com/docs/enroll-resources/machine-id/deployment/github-actions/#example-manual-configuration
